name: login_workflow
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Architecture
  cupertino_icons: ^1.0.4
  flutter_clean_architecture: ^5.0.2
  get_it: ^7.2.0

  # Utilities
  fluttertoast: ^8.0.8
  uuid: ^3.0.6
  shared_preferences: ^2.0.13

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/